services:
  - type: web
    name: home-owner-club
    env: node
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: home-owner-club-db
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
