services:
  - type: web
    name: home-owner-club
    env: node
    buildCommand: chmod +x ./render-build.sh && ./render-build.sh
    startCommand: node dist/src/main.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: home-owner-club-db
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: HUSKY_SKIP_INSTALL
        value: 1
      - key: RENDER
        value: true
