services:
  - type: web
    name: home-owner-club
    env: node
    buildCommand: npm install && npm run build:prod
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: FALLBACK_LANGUAGE
        value: en_US
      - key: DB_TYPE
        value: postgres
      - key: DB_HOST
        value: cuqppe5umphs73eukbig-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_USERNAME
        value: hocdb_h669_user
      - key: DB_PASSWORD
        value: 07ghgFiSwDYj7ymnIva8AAz8W4DeNEcU
      - key: DB_DATABASE
        value: hocdb_h669
      - key: DB_SSL
        value: "true"
